# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('credit_card_num', models.BigIntegerField()),
                ('expiry_month', models.SmallIntegerField()),
                ('expiry_year', models.SmallIntegerField()),
                ('sec_code', models.SmallIntegerField()),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_date', models.CharField(max_length=255)),
                ('movie_time', models.CharField(max_length=255)),
                ('num_tix', models.SmallIntegerField()),
                ('order_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
